# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

stages:
   - build
   - test

build:
  stage: build
  script:
    - apt-get update -y
    - apt-get install -y git cmake g++ gcovr
    - git submodule update --init --recursive
    - mkdir build && cd build
    - cmake ..
    - make -j
    # - cd ..
  cache:
    key: build-tests
    paths:
      - unit_tests
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  script:
    - ./unit_tests
    - gcovr -r ../src/
cache:
  key: build-tests
  paths:
    - unit_tests
