# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc
services: 
  - mkrrr/docker-ubuntu-vnc-desktop

stages:
   - build
   - test

cache:
  key: build
  paths:
    - build/

build:
  stage: build
  script:
    - apt-get update -y
    - apt-get install -y git cmake g++ gcovr libwxgtk3.0-gtk3-dev
    - git submodule update --init --recursive
    - mkdir build && cd build
    - cmake ..
    - make -j
    # - cd ..
  timeout: 1 hour
  artifacts:
    paths:
      - build/
  


# run tests using the binary built before
test:
  stage: test
  script:
    - cd build
    - ./unit_tests
  dependencies:
    - build
