# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  stage: build
  script:
    - apt-get update --yes
    - apt-get install --yes cmake
    - mkdir build && cd build
    - cmake ..
    - make -j
  artifacts:
    paths:
      - unit_tests
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  script:
    - ./unit_tests
